/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an anonymous buyer session
         * @description Returns a token the client stores (localStorage) and sends as
         *     `Authorization: Bearer <token>`. Holds belong to the session, so
         *     a reload with the same token restores the user's selection.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/seatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Venue layout, sections, prices
         * @description Static layout. Changes rarely; cacheable (ETag). Contains no
         *     availability. That comes from /availability.
         */
        get: operations["getSeatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which seats are unavailable, as a snapshot or a delta
         * @description Without `since`: a full snapshot.
         *     With `since`: the changes after that `seq`. If the server no
         *     longer has history that far back, it returns a snapshot instead;
         *     clients must handle both `type`s on every call.
         *
         *     "Unavailable" covers held by anyone (including the caller) and
         *     sold. Clients overlay their own holds from GET /holds.
         */
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's current holds for this event */
        get: operations["getHolds"];
        put?: never;
        /**
         * Hold one seat
         * @description Atomic: of any number of concurrent requests for the same seat,
         *     exactly one succeeds. Idempotent for the caller: holding a seat
         *     the caller already holds returns 200 with the unchanged set.
         */
        post: operations["holdSeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/holds/{seatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Release (or dismiss a revoked) hold
         * @description Idempotent: releasing a seat the caller does not hold returns 200
         *     with the unchanged set. Also used to dismiss a `revoked` hold.
         */
        delete: operations["releaseSeat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn the caller's holds into an order (stub)
         * @description Placeholder for the payment flow, which is out of scope. Rejects
         *     the request if any hold is revoked or the hold set has expired.
         */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Session: {
            token: string;
        };
        Seatmap: {
            event: components["schemas"]["Event"];
            /** @description Seat cell size in layout units; seat x/y are cell centres. */
            seat_size: number;
            bounds: components["schemas"]["Rect"];
            stage: components["schemas"]["Rect"];
            tiers: components["schemas"]["Tier"][];
            sections: components["schemas"]["Section"][];
        };
        Event: {
            id: string;
            name: string;
            venue: string;
            /** Format: date-time */
            starts_at: string;
            /**
             * @description ISO 4217, e.g. MYR
             * @example MYR
             */
            currency: string;
        };
        /** @description A price level. Several sections can share one tier. */
        Tier: {
            /** @example orch-centre */
            id: string;
            /** @example Orchestra Centre */
            name: string;
            /**
             * @description Minor units
             * @example 15000
             */
            price: number;
        };
        Section: {
            id: string;
            /** @example Orchestra Centre */
            name: string;
            /** @example Orchestra C */
            short_name: string;
            tier_id: string;
            /** @description Closed polygon in layout units, drawn at overview zoom. */
            outline: components["schemas"]["Point"][];
            rows: components["schemas"]["Row"][];
        };
        Row: {
            /** @example G */
            label: string;
            seats: components["schemas"]["Seat"][];
        };
        Seat: {
            /** @example OC-G-14 */
            id: string;
            /** @description Display label, e.g. "14" */
            number: string;
            x: number;
            y: number;
        };
        Point: [
            number,
            number
        ];
        Rect: {
            x: number;
            y: number;
            width: number;
            height: number;
        };
        /** @enum {string} */
        SeatStatus: "available" | "unavailable";
        SeatChange: {
            seat_id: string;
            status: components["schemas"]["SeatStatus"];
        };
        AvailabilitySnapshot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "snapshot";
            seq: number;
            /** Format: date-time */
            server_time: string;
            /** @description Every seat that is not available. All others are available. */
            unavailable: string[];
        };
        AvailabilityDelta: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delta";
            /** @description The seq after applying `changes`. */
            seq: number;
            /** Format: date-time */
            server_time: string;
            /** @description Net changes since `since`, one entry per seat. */
            changes: components["schemas"]["SeatChange"][];
        };
        /** @description Reverb broadcast payload (see x-realtime). */
        SeatsChanged: {
            seq: number;
            changes: components["schemas"]["SeatChange"][];
        };
        Hold: {
            seat_id: string;
            /** @enum {string} */
            status: "held" | "revoked";
        };
        HoldSet: {
            /** @description In the order the seats were held. */
            holds: components["schemas"]["Hold"][];
            /**
             * Format: date-time
             * @description Shared expiry of every hold. Null when nothing is held.
             */
            expires_at: string | null;
            /** Format: date-time */
            server_time: string;
            /** @example 10 */
            max_seats: number;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "SEAT_UNAVAILABLE" | "HOLD_LIMIT_REACHED" | "HOLDS_INVALID" | "UNAUTHENTICATED" | "NOT_FOUND" | "VALIDATION_FAILED";
                message: string;
            };
        };
    };
    responses: {
        /** @description The caller's full hold set after the operation */
        HoldSet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HoldSet"];
            };
        };
        /** @description Event (or seat) not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, unknown or expired session token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        EventId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    getSeatmap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seatmap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Seatmap"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAvailability: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot or delta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilitySnapshot"] | components["schemas"]["AvailabilityDelta"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getHolds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HoldSet"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    holdSeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    seat_id: string;
                };
            };
        };
        responses: {
            200: components["responses"]["HoldSet"];
            201: components["responses"]["HoldSet"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description `SEAT_UNAVAILABLE`: someone else holds or bought it.
             *     `HOLD_LIMIT_REACHED`: the caller already has `max_seats` holds.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    releaseSeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
                seatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HoldSet"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order created, awaiting payment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order_id: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `HOLDS_INVALID`: nothing held, a hold is revoked, or holds expired. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
